<?xml version="1.0" encoding="utf-8"?><Database Name="UAModel" Class="SQLModelDesignDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CASMP\SQLEXPRESS;Initial Catalog=UAModel;Integrated Security=True" SettingsObjectName="CAS.UA.SQLRepository.Properties.Settings" SettingsPropertyName="UAModelConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DataTypeDesign" Member="DataTypeDesigns">
    <Type Name="DataTypeDesign">
      <Column Name="DataTypeDesignIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NoArraysAllowed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NotInAddressSpace" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DataTypeDesign_ListOfEncoding" Member="ListOfEncodings" ThisKey="DataTypeDesignIndex" OtherKey="DataTypeDesignIndex" Type="ListOfEncoding" />
      <Association Name="DataTypeDesign_ListOfField" Member="ListOfFields" ThisKey="DataTypeDesignIndex" OtherKey="DataTypeDesignIndex" Type="ListOfField" />
      <Association Name="DataTypeDesign_Parameter" Member="Parameters" ThisKey="DataTypeDesignIndex" OtherKey="DataTypeDesignIndex" Type="Parameter" />
      <Association Name="DataTypeDesign_VariableDesign" Member="VariableDesigns" ThisKey="DataTypeDesignIndex" OtherKey="DataTypeDesignIndex" Type="VariableDesign" />
      <Association Name="DataTypeDesign_VariableTypeDesign" Member="VariableTypeDesigns" ThisKey="DataTypeDesignIndex" OtherKey="DataTypeDesignIndex" Type="VariableTypeDesign" />
      <Association Name="TypeDesign_DataTypeDesign" Member="TypeDesign" ThisKey="DataTypeDesignIndex" OtherKey="NodeIndex" Type="TypeDesign" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VariableValue" Member="VariableValues">
    <Type Name="VariableValue">
      <Column Name="NodeIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Object" DbType="Variant" CanBeNull="true" />
      <Column Name="TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="Quality" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="VariableDesign_VariableValue" Member="VariableDesign" ThisKey="NodeIndex" OtherKey="NodeIndex" Type="VariableDesign" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DefaultValue" Member="DefaultValues">
    <Type Name="DefaultValue">
      <Column Name="DefaultValueIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Value" Type="System.Object" DbType="Variant" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="DefaultValue_VariableDesign" Member="VariableDesigns" ThisKey="DefaultValueIndex" OtherKey="DefaultValueIndex" Type="VariableDesign" />
    </Type>
  </Table>
  <Table Name="dbo.InformationsModel" Member="InformationsModels">
    <Type Name="InformationsModel">
      <Column Name="InformationsModelIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NameNS" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="InformationsModel_ModelDesign" Member="ModelDesigns" ThisKey="InformationsModelIndex" OtherKey="InformationsModelIndex" Type="ModelDesign" />
      <Association Name="InformationsModel_TopLevelObject" Member="TopLevelObjects" ThisKey="InformationsModelIndex" OtherKey="InformationsModelIndex" Type="TopLevelObject" />
    </Type>
  </Table>
  <Table Name="dbo.InputArguments" Member="InputArguments">
    <Type Name="InputArgument">
      <Column Name="ParameterIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MethodDesignIndex" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="InputArgument_Parameter" Member="Parameter" ThisKey="ParameterIndex" OtherKey="ParameterIndex" Type="Parameter" Cardinality="One" />
      <Association Name="MethodDesign_InputArgument" Member="MethodDesign" ThisKey="MethodDesignIndex" OtherKey="NodeIndex" Type="MethodDesign" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InstanceDesign" Member="InstanceDesigns">
    <Type Name="InstanceDesign">
      <Column Name="NodeIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="InstanceDesign_NodeDesign" Member="NodeDesign" ThisKey="NodeIndex" OtherKey="NodeDesignIndex" Type="NodeDesign" Cardinality="One" />
      <Association Name="InstanceDesign_ObjectDesign" Member="ObjectDesign" ThisKey="NodeIndex" OtherKey="NodeIndex" Type="ObjectDesign" Cardinality="One" />
      <Association Name="MethodDesign_InstanceDesign" Member="MethodDesign" ThisKey="NodeIndex" OtherKey="NodeIndex" Type="MethodDesign" IsForeignKey="true" />
      <Association Name="VariableDesign_InstanceDesign" Member="VariableDesign" ThisKey="NodeIndex" OtherKey="NodeIndex" Type="VariableDesign" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ListOfChildren" Member="ListOfChildrens">
    <Type Name="ListOfChildren">
      <Column Name="NodeDesignIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Parent" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="ListOfChildren_NodeDesign" Member="NodeDesign1" ThisKey="NodeDesignIndex" OtherKey="NodeDesignIndex" Type="NodeDesign" Cardinality="One" />
      <Association Name="NodeDesign_ListOfChildren" Member="NodeDesign" ThisKey="Parent" OtherKey="NodeDesignIndex" Type="NodeDesign" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ListOfEncodings" Member="ListOfEncodings">
    <Type Name="ListOfEncoding">
      <Column Name="DataTypeDesignIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="NodeIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="DataTypeDesign_ListOfEncoding" Member="DataTypeDesign" ThisKey="DataTypeDesignIndex" OtherKey="DataTypeDesignIndex" Type="DataTypeDesign" IsForeignKey="true" />
      <Association Name="ObjectDesign_ListOfEncoding" Member="ObjectDesign" ThisKey="NodeIndex" OtherKey="NodeIndex" Type="ObjectDesign" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ListOfFields" Member="ListOfFields">
    <Type Name="ListOfField">
      <Column Name="DataTypeDesignIndex" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ParameterIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ListOfField_Parameter" Member="Parameter" ThisKey="ParameterIndex" OtherKey="ParameterIndex" Type="Parameter" Cardinality="One" />
      <Association Name="DataTypeDesign_ListOfField" Member="DataTypeDesign" ThisKey="DataTypeDesignIndex" OtherKey="DataTypeDesignIndex" Type="DataTypeDesign" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MethodDesign" Member="MethodDesigns">
    <Type Name="MethodDesign">
      <Column Name="NodeIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NonExecutable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="MethodDesign_InputArgument" Member="InputArguments" ThisKey="NodeIndex" OtherKey="MethodDesignIndex" Type="InputArgument" />
      <Association Name="MethodDesign_InstanceDesign" Member="InstanceDesign" ThisKey="NodeIndex" OtherKey="NodeIndex" Type="InstanceDesign" Cardinality="One" />
      <Association Name="MethodDesign_OutputArgument" Member="OutputArguments" ThisKey="NodeIndex" OtherKey="MethodDesignIndex" Type="OutputArgument" />
    </Type>
  </Table>
  <Table Name="dbo.ModelDesign" Member="ModelDesigns">
    <Type Name="ModelDesign">
      <Column Name="ModelDesignIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InformationsModelIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TargetNamespace" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TargetXmlNamespace" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="DefaultLocale" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="ModelDesign_Namespace" Member="Namespaces" ThisKey="ModelDesignIndex" OtherKey="ModelDesignIndex" Type="Namespace" />
      <Association Name="ModelDesign_NodeDesign" Member="NodeDesigns" ThisKey="ModelDesignIndex" OtherKey="ModelDesignIndex" Type="NodeDesign" />
      <Association Name="InformationsModel_ModelDesign" Member="InformationsModel" ThisKey="InformationsModelIndex" OtherKey="InformationsModelIndex" Type="InformationsModel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Namespace" Member="Namespaces">
    <Type Name="Namespace">
      <Column Name="ModelDesignIndex" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Prefix" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="InternalPrefix" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="XmlNamespace" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="XmlPrefix" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="FilePath" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="ModelDesign_Namespace" Member="ModelDesign" ThisKey="ModelDesignIndex" OtherKey="ModelDesignIndex" Type="ModelDesign" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NodeDesign" Member="NodeDesigns">
    <Type Name="NodeDesign">
      <Column Name="BrowseName" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="DisplayNameKey" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="DescriptionKey" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NodeDesignIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SymbolicName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="SymbolicNameNS" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="SymbolicId" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="SymbolicIdNS" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="IsDeclaration" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NumericId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WriteAccess" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModelDesignIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="NodeDesign_ListOfChildren" Member="ListOfChildrens" ThisKey="NodeDesignIndex" OtherKey="Parent" Type="ListOfChildren" />
      <Association Name="NodeDesign_Reference" Member="References" ThisKey="NodeDesignIndex" OtherKey="Parent" Type="Reference" />
      <Association Name="NodeDesign_Reference1" Member="References1" ThisKey="NodeDesignIndex" OtherKey="Target" Type="Reference" />
      <Association Name="NodeDesign_Reference2" Member="References2" ThisKey="NodeDesignIndex" OtherKey="Type" Type="Reference" />
      <Association Name="NodeDesign_TopLevelObject" Member="TopLevelObject" ThisKey="NodeDesignIndex" OtherKey="NodeDesignIndex" Type="TopLevelObject" Cardinality="One" />
      <Association Name="NodeDesign_TypeDesign" Member="TypeDesigns" ThisKey="NodeDesignIndex" OtherKey="BaseType" Type="TypeDesign" />
      <Association Name="InstanceDesign_NodeDesign" Member="InstanceDesign" ThisKey="NodeDesignIndex" OtherKey="NodeIndex" Type="InstanceDesign" IsForeignKey="true" />
      <Association Name="ListOfChildren_NodeDesign" Member="ListOfChildren" ThisKey="NodeDesignIndex" OtherKey="NodeDesignIndex" Type="ListOfChildren" IsForeignKey="true" />
      <Association Name="ModelDesign_NodeDesign" Member="ModelDesign" ThisKey="ModelDesignIndex" OtherKey="ModelDesignIndex" Type="ModelDesign" IsForeignKey="true" />
      <Association Name="TypeDesign_NodeDesign" Member="TypeDesign" ThisKey="NodeDesignIndex" OtherKey="NodeIndex" Type="TypeDesign" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ObjectDesign" Member="ObjectDesigns">
    <Type Name="ObjectDesign">
      <Column Name="NodeIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SupportsEvents" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="ObjectDesign_ListOfEncoding" Member="ListOfEncodings" ThisKey="NodeIndex" OtherKey="NodeIndex" Type="ListOfEncoding" />
      <Association Name="InstanceDesign_ObjectDesign" Member="InstanceDesign" ThisKey="NodeIndex" OtherKey="NodeIndex" Type="InstanceDesign" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ObjectTypeDesign" Member="ObjectTypeDesigns">
    <Type Name="ObjectTypeDesign">
      <Column Name="NodeIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SupportsEvents" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TypeDesign_ObjectTypeDesign" Member="TypeDesign" ThisKey="NodeIndex" OtherKey="NodeIndex" Type="TypeDesign" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OutputArguments" Member="OutputArguments">
    <Type Name="OutputArgument">
      <Column Name="ParameterIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MethodDesignIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="MethodDesign_OutputArgument" Member="MethodDesign" ThisKey="MethodDesignIndex" OtherKey="NodeIndex" Type="MethodDesign" IsForeignKey="true" />
      <Association Name="Parameter_OutputArgument" Member="Parameter" ThisKey="ParameterIndex" OtherKey="ParameterIndex" Type="Parameter" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Parameter" Member="Parameters">
    <Type Name="Parameter">
      <Column Name="ParameterIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="DescriptionKey" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Identifier" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataTypeDesignIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ValueRank" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Parameter_OutputArgument" Member="OutputArgument" ThisKey="ParameterIndex" OtherKey="ParameterIndex" Type="OutputArgument" Cardinality="One" />
      <Association Name="DataTypeDesign_Parameter" Member="DataTypeDesign" ThisKey="DataTypeDesignIndex" OtherKey="DataTypeDesignIndex" Type="DataTypeDesign" IsForeignKey="true" />
      <Association Name="InputArgument_Parameter" Member="InputArgument" ThisKey="ParameterIndex" OtherKey="ParameterIndex" Type="InputArgument" IsForeignKey="true" />
      <Association Name="ListOfField_Parameter" Member="ListOfField" ThisKey="ParameterIndex" OtherKey="ParameterIndex" Type="ListOfField" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PropertyValue" Member="PropertyValues">
    <Type Name="PropertyValue">
      <Column Name="NodeIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Object" DbType="Variant" CanBeNull="true" />
      <Column Name="TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Association Name="VariableDesign_PropertyValue" Member="VariableDesign" ThisKey="NodeIndex" OtherKey="NodeIndex" Type="VariableDesign" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[References]" Member="References">
    <Type Name="Reference">
      <Column Name="ReferenceIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Parent" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Target" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="NodeDesign_Reference" Member="NodeDesign" ThisKey="Parent" OtherKey="NodeDesignIndex" Type="NodeDesign" IsForeignKey="true" />
      <Association Name="NodeDesign_Reference1" Member="NodeDesign1" ThisKey="Target" OtherKey="NodeDesignIndex" Type="NodeDesign" IsForeignKey="true" />
      <Association Name="NodeDesign_Reference2" Member="NodeDesign2" ThisKey="Type" OtherKey="NodeDesignIndex" Type="NodeDesign" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReferenceTypeDesign" Member="ReferenceTypeDesigns">
    <Type Name="ReferenceTypeDesign">
      <Column Name="ReferenceTypeDesignIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InverseName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="InverseNameKey" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Symmetric" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="ReferenceTypeDesign_TypeDesign" Member="TypeDesign" ThisKey="ReferenceTypeDesignIndex" OtherKey="NodeIndex" Type="TypeDesign" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.TopLevelObjects" Member="TopLevelObjects">
    <Type Name="TopLevelObject">
      <Column Name="InformationsModelIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="NodeDesignIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="InformationsModel_TopLevelObject" Member="InformationsModel" ThisKey="InformationsModelIndex" OtherKey="InformationsModelIndex" Type="InformationsModel" IsForeignKey="true" />
      <Association Name="NodeDesign_TopLevelObject" Member="NodeDesign" ThisKey="NodeDesignIndex" OtherKey="NodeDesignIndex" Type="NodeDesign" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TypeDesign" Member="TypeDesigns">
    <Type Name="TypeDesign">
      <Column Name="NodeIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClassName" Type="System.Object" DbType="Variant" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BaseType" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="TypeDesign_DataTypeDesign" Member="DataTypeDesign" ThisKey="NodeIndex" OtherKey="DataTypeDesignIndex" Type="DataTypeDesign" Cardinality="One" />
      <Association Name="TypeDesign_NodeDesign" Member="NodeDesign" ThisKey="NodeIndex" OtherKey="NodeDesignIndex" Type="NodeDesign" Cardinality="One" />
      <Association Name="TypeDesign_ObjectTypeDesign" Member="ObjectTypeDesign" ThisKey="NodeIndex" OtherKey="NodeIndex" Type="ObjectTypeDesign" Cardinality="One" />
      <Association Name="NodeDesign_TypeDesign" Member="NodeDesign1" ThisKey="BaseType" OtherKey="NodeDesignIndex" Type="NodeDesign" IsForeignKey="true" />
      <Association Name="ReferenceTypeDesign_TypeDesign" Member="ReferenceTypeDesign" ThisKey="NodeIndex" OtherKey="ReferenceTypeDesignIndex" Type="ReferenceTypeDesign" IsForeignKey="true" />
      <Association Name="VariableTypeDesign_TypeDesign" Member="VariableTypeDesign" ThisKey="NodeIndex" OtherKey="NodeIndex" Type="VariableTypeDesign" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VariableDesign" Member="VariableDesigns">
    <Type Name="VariableDesign">
      <Column Name="NodeIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DefaultValueIndex" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DataTypeDesignIndex" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ValueRank" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ArrayDimensions" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MinimumSamplingInterval" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Historizing" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsProperty" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="VariableDesign_VariableValue" Member="VariableValues" ThisKey="NodeIndex" OtherKey="NodeIndex" Type="VariableValue" />
      <Association Name="VariableDesign_InstanceDesign" Member="InstanceDesign" ThisKey="NodeIndex" OtherKey="NodeIndex" Type="InstanceDesign" Cardinality="One" />
      <Association Name="VariableDesign_PropertyValue" Member="PropertyValues" ThisKey="NodeIndex" OtherKey="NodeIndex" Type="PropertyValue" />
      <Association Name="DataTypeDesign_VariableDesign" Member="DataTypeDesign" ThisKey="DataTypeDesignIndex" OtherKey="DataTypeDesignIndex" Type="DataTypeDesign" IsForeignKey="true" />
      <Association Name="DefaultValue_VariableDesign" Member="DefaultValue" ThisKey="DefaultValueIndex" OtherKey="DefaultValueIndex" Type="DefaultValue" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VariableTypeDesign" Member="VariableTypeDesigns">
    <Type Name="VariableTypeDesign">
      <Column Name="NodeIndex" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DefaultValue" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DataTypeDesignIndex" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ValueRank" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ArrayDimensions" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MinimumSamplingInterval" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Historizing" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ExposesItsChildren" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="VariableTypeDesign_TypeDesign" Member="TypeDesign" ThisKey="NodeIndex" OtherKey="NodeIndex" Type="TypeDesign" Cardinality="One" />
      <Association Name="DataTypeDesign_VariableTypeDesign" Member="DataTypeDesign" ThisKey="DataTypeDesignIndex" OtherKey="DataTypeDesignIndex" Type="DataTypeDesign" IsForeignKey="true" />
    </Type>
  </Table>
</Database>